export type Role='ADMIN'|'REGISTRAR'|'FINANCE';
export interface Branch{id:string;name:string;code:string;active:boolean}
export interface Specialty{id:string;name:string;code:string;active:boolean;durationValue:number;durationUnit:'day'|'week'|'month';billingMode:'one_time'|'monthly';courseFee:number;monthlyFee:number}
export interface SpecialtyBranch{specialtyId:string;branchId:string;active:boolean}
export interface PaymentMethod{id:string;name:string;logoDataUrl?:string|null;active:boolean}
export interface Bootstrap{initialized:boolean;branches:Branch[];specialties:Specialty[];specialtyBranches:SpecialtyBranch[];paymentMethods:PaymentMethod[];centerName:string;centerLogoDataUrl?:string|null}
export interface UserSession{id:string;name:string;role:Role;branchId?:string|null}
export interface LoginResult{token:string;user:UserSession}
export interface RegistrationInput{fullName:string;phone?:string;secondaryPhone?:string;branchId:string;specialtyId:string;startDate:string;paymentAmount:number;paymentMethodId?:string;paymentDate?:string;paymentDescription?:string;notes?:string}
export interface AddPaymentInput{enrollmentId:string;amount:number;paymentMethodId:string;paymentDate?:string;description?:string}
export interface RegistrationResult{studentId:string;enrollmentId:string;registerNumber:number;receipt?:Receipt}
export interface Receipt{receiptNumber:number;studentName:string;specialtyName:string;branchName:string;registerNumber:number;amount:number;remaining:number;methodName:string;issuedAt:string;centerName:string;centerPhone1?:string|null;centerPhone2?:string|null;centerAddress?:string|null;centerLogoDataUrl?:string|null;periodLabel?:string|null;description?:string|null}
export interface CenterSettings{centerName:string;phone1:string;phone2?:string|null;address?:string|null;logoDataUrl?:string|null;endingSoonDays:number;receiptLast:number}
export interface SpecialtySetting extends Specialty{description?:string|null;branchIds:string[]}
export interface UserListItem{id:string;name:string;role:Role;branchId?:string|null;active:boolean;lastLoginAt?:string|null}
export interface RegisterSequenceItem{branchId:string;branchName:string;specialtyId:string;specialtyName:string;lastNumber:number}
export interface SettingsSnapshot{center:CenterSettings;branches:Branch[];specialties:SpecialtySetting[];paymentMethods:PaymentMethod[];users:UserListItem[];sequences:RegisterSequenceItem[]}
export interface ChartPoint{label:string;value:number}
export interface FinanceReport{totalIncome:number;paymentCount:number;averagePayment:number;outstanding:number;timeline:ChartPoint[];byBranch:ChartPoint[];bySpecialty:ChartPoint[];byMethod:ChartPoint[]}
export interface Row{[key:string]:string|number|null}
export interface StudentEnrollment{id:string;specialtyName:string;branchName:string;registerNumber:number;startDate:string;endDate:string;billingMode:string;totalRequired:number;paid:number;remaining:number;status:string}
export interface StudentPayment{id:string;enrollmentId:string;receiptNumber?:number|null;amount:number;methodName:string;paidAt:string;description?:string|null;status:string}
export interface BillingPeriod{id:string;enrollmentId:string;periodNumber:number;periodStart:string;periodEnd:string;dueDate:string;amountDue:number;paid:number;remaining:number;status:string}
export interface StudentDetails{student:{id:string;fullName:string;phone?:string|null;secondaryPhone?:string|null;notes?:string|null};enrollments:StudentEnrollment[];payments:StudentPayment[];billingPeriods:BillingPeriod[]}
