import{useRef,useState}from'react';
import html2canvas from'html2canvas';
import{jsPDF}from'jspdf';
import{save}from'@tauri-apps/plugin-dialog';
import{writeFile}from'@tauri-apps/plugin-fs';
import{Download,Printer,X}from'lucide-react';
import{toast}from'sonner';
import{Button}from'../../components/ui';
import{date,money}from'../../lib/format';
import{EFC_LOGO_DATA_URL,EFC_PHONE,EFC_TEACHER,EFC_WHATSAPP}from'../../lib/brand';
import type{BillingPeriod,Bootstrap,StudentEnrollment}from'../../types';

const labels:Record<string,string>={paid:'مدفوع',partial:'دفع جزئي',due:'مستحق',overdue:'متأخر',upcoming:'لم يحن بعد'};
async function waitForImages(root:HTMLElement){await Promise.all([...root.querySelectorAll('img')].map(img=>img.complete&&img.naturalWidth>0?Promise.resolve():new Promise<void>(resolve=>{img.onload=()=>resolve();img.onerror=()=>resolve();window.setTimeout(resolve,1200)})))}

export function MonthlyStatementDialog({studentName,enrollment,periods,data,close}:{studentName:string;enrollment:StudentEnrollment;periods:BillingPeriod[];data:Bootstrap;close:()=>void}){
  const ref=useRef<HTMLDivElement>(null);const[busy,setBusy]=useState(false);const logo=data.centerLogoDataUrl||EFC_LOGO_DATA_URL;
  async function pdf(){if(!ref.current)return;setBusy(true);try{await waitForImages(ref.current);const canvas=await html2canvas(ref.current,{scale:2.4,backgroundColor:'#fff',logging:false});const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true});const pw=doc.internal.pageSize.getWidth(),ph=doc.internal.pageSize.getHeight(),margin=7,ratio=Math.min((pw-margin*2)/canvas.width,(ph-margin*2)/canvas.height),w=canvas.width*ratio,h=canvas.height*ratio;doc.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',(pw-w)/2,(ph-h)/2,w,h);const bytes=new Uint8Array(doc.output('arraybuffer'));const path=await save({defaultPath:`كشف-الأشهر-${studentName.replace(/\s+/g,'-')}.pdf`,filters:[{name:'PDF',extensions:['pdf']}]});if(path){await writeFile(path,bytes);toast.success('تم حفظ كشف الأشهر PDF.')}}catch(e){console.error(e);toast.error('تعذر إنشاء كشف الأشهر.')}finally{setBusy(false)}}
  return <div className="overlay statement-overlay"><div className="dialog approved-receipt-dialog"><div className="dialog-top no-print"><div><p>الروسي</p><b>كشف أشهر الدورة</b></div><button className="icon-button" onClick={close}><X/></button></div><div className="approved-receipt statement-receipt receipt-print-root" ref={ref}><div className="receipt-head"><div className="receipt-contact-block"><img src={logo} alt="EFC"/><div><b>Tél: {EFC_PHONE}</b><b>WhatsApp: {EFC_WHATSAPP}</b><small>{EFC_TEACHER}</small></div></div><div className="receipt-center-title"><h1><span>Centre EFC</span><span>مركز</span></h1><p>جميع الشهادات معترف بها من طرف الدولة</p><div className="statement-title">كشف الأشهر</div></div><div className="receipt-logo-only"><img src={logo} alt="EFC"/></div></div><div className="receipt-meta"><span>البداية: <b>{date(`${enrollment.startDate}T12:00:00`)}</b></span><span>الفرع: <b>{enrollment.branchName}</b></span></div><div className="statement-student"><span>اسم الطالب <b>{studentName}</b></span><span>التخصص <b>{enrollment.specialtyName}</b></span><span>رقم السجل <b>{String(enrollment.registerNumber).padStart(4,'0')}</b></span></div><table className="statement-table"><thead><tr><th>الشهر</th><th>تاريخ الاستحقاق</th><th>المبلغ</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th></tr></thead><tbody>{periods.map(p=><tr key={p.id}><td>الشهر {p.periodNumber}</td><td>{date(`${p.dueDate}T12:00:00`)}</td><td>{money(p.amountDue)}</td><td>{money(p.paid)}</td><td>{money(p.remaining)}</td><td><span className={`status ${p.status}`}>{labels[p.status]||p.status}</span></td></tr>)}</tbody></table><div className="statement-total"><b>إجمالي المدفوع: {money(enrollment.paid)}</b><b>المتبقي من الدورة: {money(enrollment.remaining)}</b></div><p className="receipt-warning">ملاحظة 1: لا يمكن استرجاع المبلغ المدفوع للمركز في أي حال من الأحوال.</p></div><div className="actions no-print"><Button className="secondary" onClick={()=>window.print()}><Printer size={16}/>طباعة</Button><Button disabled={busy} onClick={()=>void pdf()}><Download size={16}/>{busy?'جارٍ إنشاء PDF…':'تحميل PDF'}</Button><Button className="secondary" onClick={close}>إغلاق</Button></div></div></div>
}
